[build]
  command = "cd Frontend && npm install && npm run build" # Your original build command
  publish = "Frontend/dist/coreui-free-angular-admin-template" # Your publish directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200