[build]
  base = "."
  publish = "Frontend/dist/coreui-free-angular-admin-template"
  command = "cd Frontend && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
